FROM nazar-base

USER root
COPY bridges/web/ bridges/web/
RUN npm -w bridges/web run build
USER nazar

ENV NAZAR_UI_PORT=3000
ENV NAZAR_OBJECTS_DIR=/data/objects
ENV NAZAR_PI_MODEL=""
ENV NAZAR_PI_TRANSPORT=""
ENV NAZAR_PERSONA_DIR=/usr/local/share/nazar/persona

CMD ["node", "bridges/web/dist/index.js"]
